### ISSUE TITLE
Wrongly imported humidity sensor

### ISSUE THREAD

**Issue by Puebllo** [anarion80/tech#5]
Hi,
Amazing job, reviving this integration project! I've just migrated from original integration to your's and wanted to check if the wireless thermostat data such as battery level and signal strength are available. Unfortunately they're not. In emodul I can see battery level and signal strength (represent with "bars")
Please tell me, are those features are already in your fork or are they in development  ?

I've TECH: L4-WiFi (v.1.1.10) controller and TECH R-8b Wireless thermostats for each area. Below is example of attributes from thermostat:

```hvac_modes:
  - heat
  - "off"
min_temp: 7
max_temp: 35
current_temperature: 22.6
temperature: 21.5
current_humidity: -2
hvac_action: idle
friendly_name: Biuro
supported_features: 385```

**Comment by anarion80** [comment]
Hello. 

Not sure what you mean exactly. Battery level for wireless sensors is extracted as separate sensor under device:
![image](https://github.com/anarion80/tech/assets/2185791/0839ad00-3e9f-4ae1-b477-f051acad0ef7)

Signal strength is currently not extracted.

PS. I was added as collaborator to the upstream repo, so this repo will become obsolete and everything will happen in the upstream:
https://github.com/mariusz-ostoja-swierczynski/tech-controllers/pull/55

**Comment by Puebllo** [comment]
Oh, now I see them in UI. I was too quick with issue. Thanks! 

I've one extra sensor for humidity that shows -2% in all areas.

**Comment by anarion80** [comment]
Ok, for humidity it would be great if you could provide a json dump of what emodul is returning for your module.
Go to emodul.pl while logged in, developer tools (F12), network tab, refresh page and then look for XHR type request to your module id. Click on it and get the JSON response:
![image](https://github.com/anarion80/tech/assets/2185791/d6fdcf72-bda2-440a-9018-a4810ad85a37)

**Comment by Puebllo** [comment]
JSON response is quite long, so I've putted it here: https://pastebin.com/TmseCEUb

(I've redacted controller id, rest of the response is untouched)

**Comment by anarion80** [comment]
Ok, so the API is reporting "-2" for each of 8 sensors. What does that translate into in emodul itself?

**Comment by Puebllo** [comment]
emodul doesn't show anything regarding humidity

![image](https://github.com/anarion80/tech/assets/22179495/401d6c66-32bc-4122-9adf-f2b0fb85f6c7)

**Comment by anarion80** [comment]
All right, then it seems like some error value on their side as well.  Right now I only check if humidity is reported and if it is different than zero. I will need to then check if it is greater than zero, and then you will not have such sensor entity.

**Comment by Puebllo** [comment]
Perfect, let me know when it's ready then I'll test it

**Comment by anarion80** [comment]
Ok, it is fixed now on the main branch. You can download and test.

**Comment by Puebllo** [comment]
Works good, no humidity sensor and no errors in logs 👌
