### ISSUE TITLE
Support for reading actuators from zone

### ISSUE THREAD

**Issue by cor73x** [anarion80/tech#7]
First, thank you for taking care of this integration :) 

I have small request, I have few actuators on my radiators, and it would be nice to read battery level and valve open status in HA. 
Can you add this? 

In json file, it is in: 
zones.elements.[].actuators - battery level, signal strength. 
Open level: zones.elements.[].zone.actuatorsOpen (0-100%). 

You can have more than one actuator in zone, but open level is same for all actuators as there is only one value in json.

In demo app it is visible here: 
![image](https://github.com/anarion80/tech/assets/3730619/40525f6d-4964-4ec9-a76b-54cb55557aca)
![image](https://github.com/anarion80/tech/assets/3730619/3ae5461f-f31a-4a83-b607-b77bd51dd8d7)

Probably those can be added as "valves" and battery level/signal strength as attributes? you are unable to control actuator from emodul, so maybe just sensors will be enough. 

Thanks!

**Comment by anarion80** [comment]
Sure, but please open this issue in the original repo: https://github.com/mariusz-ostoja-swierczynski/tech-controllers/, as this one was only temporary and development will continue in that original repo. I will consider this after [v2](https://github.com/mariusz-ostoja-swierczynski/tech-controllers/pull/55) is merged some time next week.
